WARNING:root:You are using solc version 0.7.6, The latest supported version is 0.4.19
INFO:CryticCompile:Compilation warnings/errors on /sb/0xb246bcd5baac8e342941d0f803d528b6668e42cd.sol:
Warning: Unused local variable.
   --> /sb/0xb246bcd5baac8e342941d0f803d528b6668e42cd.sol:593:24:
    |
593 |         (bool success, bytes memory returndata) = governance.call(_setupData);
    |                        ^^^^^^^^^^^^^^^^^^^^^^^


incomplete push instruction at 55
incomplete push instruction at 77
incomplete push instruction at 71
INFO:root:contract /sb/0xb246bcd5baac8e342941d0f803d528b6668e42cd.sol:SafeERC20:
INFO:symExec:	============ Results ===========
INFO:symExec:	  EVM Code Coverage: 			 37.0%
INFO:symExec:	  Integer Underflow: 			 False
INFO:symExec:	  Integer Overflow: 			 False
INFO:symExec:	  Parity Multisig Bug 2: 		 False
INFO:symExec:	  Callstack Depth Attack Vulnerability:  False
INFO:symExec:	  Transaction-Ordering Dependence (TOD): False
INFO:symExec:	  Timestamp Dependency: 		 False
INFO:symExec:	  Re-Entrancy Vulnerability: 		 False
INFO:symExec:	====== Analysis Completed ======
INFO:root:contract /sb/0xb246bcd5baac8e342941d0f803d528b6668e42cd.sol:Address:
INFO:symExec:	============ Results ===========
INFO:symExec:	  EVM Code Coverage: 			 37.0%
INFO:symExec:	  Integer Underflow: 			 False
INFO:symExec:	  Integer Overflow: 			 False
INFO:symExec:	  Parity Multisig Bug 2: 		 False
INFO:symExec:	  Callstack Depth Attack Vulnerability:  False
INFO:symExec:	  Transaction-Ordering Dependence (TOD): False
INFO:symExec:	  Timestamp Dependency: 		 False
INFO:symExec:	  Re-Entrancy Vulnerability: 		 False
INFO:symExec:	====== Analysis Completed ======
INFO:root:contract /sb/0xb246bcd5baac8e342941d0f803d528b6668e42cd.sol:UniCatFarm:
INFO:symExec:	============ Results ===========
Traceback (most recent call last):
  File "/oyente/oyente/oyente.py", line 232, in <module>
    main()
  File "/oyente/oyente/oyente.py", line 227, in main
    exit_code = analyze_solidity()
  File "/oyente/oyente/oyente.py", line 110, in analyze_solidity
    results, exit_code = run_solidity_analysis(inputs)
  File "/oyente/oyente/oyente.py", line 87, in run_solidity_analysis
    result, return_code = symExec.run(disasm_file=inp['disasm_file'], source_map=inp['source_map'], source_file=inp['source'])
  File "/oyente/oyente/symExec.py", line 2458, in run
    analyze()
  File "/oyente/oyente/symExec.py", line 2441, in analyze
    run_build_cfg_and_analyze(timeout_cb=timeout_cb)
  File "/oyente/oyente/symExec.py", line 2398, in run_build_cfg_and_analyze
    build_cfg_and_analyze()
  File "/oyente/oyente/symExec.py", line 225, in build_cfg_and_analyze
    collect_vertices(tokens)
  File "/oyente/oyente/symExec.py", line 341, in collect_vertices
    idx = mapping_non_push_instruction(current_line_content, current_ins_address, idx, positions, length) if g_src_map else None
  File "/oyente/oyente/symExec.py", line 281, in mapping_non_push_instruction
    raise RuntimeError(F"Source map error, unknown name({name}) or instr_name({instr_name})")
RuntimeError: Source map error, unknown name(SHR) or instr_name(INVALID)
